# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative permalinks: true
plugins: [jekyll-paginate, 'jekyll/scholar']

# Setup
title:               J. Z. Downs
tagline:             'Sums and summits'
description:         'A place code, math, and visualizations.'
url:                 https://jacobdowns.github.io/'
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Jacob Downs
  email:             jacob.downs@umontana.edu

# Custom vars
version:             1.0.0
