# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink:            /

# Setup
title:               J. Z. Downs
tagline:             'Computational Mathematician'
description:         'A place for code projects, math, and visualizations.'
url:                 https://jacobdowns.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jacob Downs
  email:             jacob.downs@umontana.edu

# Custom vars
version:             1.0.0
